# Generated by Django 4.1.4 on 2023-01-26 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
