# Generated by Django 4.1.4 on 2023-01-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('send', 'Send'), ('accepted', 'Accepted')], max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=225)),
                ('last_name', models.CharField(blank=True, max_length=225)),
                ('email', models.EmailField(max_length=200)),
                ('bio', models.TextField(default='No bio', max_length=300)),
                ('profile_picture', models.ImageField(default='profile_pic.jpg', upload_to='profile_pictures/')),
                ('country', models.CharField(max_length=225)),
                ('fav_field_os', models.CharField(blank=True, max_length=225)),
                ('followers', models.CharField(blank=True, max_length=225)),
                ('following', models.CharField(blank=True, max_length=225)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('profile_type', models.CharField(blank=True, max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
