# Generated by Django 4.1.4 on 2023-01-24 09:44

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('send', 'Send'), ('accepted', 'Accepted')], max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=225)),
                ('last_name', models.CharField(blank=True, max_length=225)),
                ('email', models.EmailField(blank=True, max_length=200, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('bio', models.TextField(blank=True, default='No bio', max_length=300)),
                ('profile_image', models.ImageField(blank=True, default=main.models.get_default_profile_image, max_length=255, null=True, upload_to=main.models.get_profile_image_filepath)),
                ('country', models.CharField(blank=True, max_length=225)),
                ('fav_field_os', models.CharField(blank=True, max_length=225)),
                ('followers', models.CharField(blank=True, max_length=225)),
                ('following', models.CharField(blank=True, max_length=225)),
                ('profile_type', models.CharField(blank=True, max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hide_email', models.BooleanField(default=True)),
            ],
        ),
    ]
