# Generated by Django 4.1.4 on 2022-12-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_followers_alter_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
