# Generated by Django 4.1.4 on 2023-02-11 21:16

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to=chat.models.get_message_file)),
                ('media_caption', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('link_caption', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=chat.models.get_message_file)),
                ('doc_caption', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
