# Generated by Django 4.1.4 on 2023-02-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_options_conversation_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
