# Generated by Django 4.1.4 on 2023-01-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ('created_at',)},
        ),
    ]
