# Generated by Django 4.1.4 on 2023-02-13 13:49

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='doc_caption',
        ),
        migrations.RemoveField(
            model_name='message',
            name='link_caption',
        ),
        migrations.RemoveField(
            model_name='message',
            name='media_caption',
        ),
        migrations.RemoveField(
            model_name='message',
            name='media_file',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.get_message_file),
        ),
    ]
