# Generated by Django 4.1.4 on 2023-01-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_messageattachment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'ordering': ('-created_at',)},
        ),
    ]
