# Generated by Django 3.2.12 on 2022-12-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='friends',
            new_name='connections',
        ),
    ]
