name: Build and Push

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: ${{ secrets.DOCKER_HUB_REPOSITORY }}
        tags: django-app:latest,mysql:latest

env:
  DOCKER_HUB_USERNAME: iamenochchirima
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  DOCKER_HUB_REPOSITORY: iamenochchirima/exodt

  DB_NAME: mysql
  DB_USER: root
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
