name: Build and Push

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: iamenochchirima
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Images
      uses: docker/build-push-action@v1
      with:
        repository: iamenochchirima/exodt
        tags: django-app:latest,mysql:latest
env:
  DB_NAME: mysql
  DB_USER: root
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

