name: Django 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run the app
        run: |
          docker-compose build
          docker-compose up -d
      - name: Run Django migrations
        run: |
          docker-compose exec -T app python manage.py migrate
