name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: mysql
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python $
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Docker and docker-compose
      uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: '1.29.2'

    - name: Build and run Docker containers with docker-compose
      run: docker-compose build
      run: docker-compose up
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env: 
        DB_ENGINE: django.db.backends.mysql
        DB_NAME: mysql
        DB_USER: root
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
    - name: Build Docker Image
      run: docker build -t exodt:app .
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push Docker Image
      run: docker push exodt:app
